import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  card: {
    backgroundColor: 'transparent',
    borderRadius: 24,
    paddingHorizontal: 22,
    paddingVertical: 8,
    shadowColor: 'transparent',
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    alignSelf: 'center',
    width: '88%',
    maxWidth: 420,
    marginTop: 6,
  },
  brandTitle: {
    fontSize: 46,
    fontWeight: '800',
    color: '#E44EA1',
    textAlign: 'center',
  },
  brandSubtitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#D6336C',
    textAlign: 'center',
    marginBottom: 12,
  },
  description: {
    color: '#6F4A6E',
    textAlign: 'center',
    fontSize: 16,
    marginBottom: 24,
    lineHeight: 24,
  },
  descriptionStrong: {
    color: '#4b2a3a',
    textAlign: 'center',
    fontSize: 15,
    marginBottom: 18,
    lineHeight: 22,
    fontWeight: '500',
  },
  inputWrapper: {
    marginBottom: 14,
    position: 'relative',
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingLeft: 48,
    height: 48,
    fontSize: 16,
    color: '#2B1B2E',
    borderWidth: 1,
    borderColor: '#ECD1E2',
  },
  inputIcon: {
    position: 'absolute',
    left: 12,
    top: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputIconText: {
    color: '#9C1F54',
  },
  primaryButton: {
    backgroundColor: '#E44EA1',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
    shadowColor: '#E44EA1',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  googleButton: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginTop: 14,
    borderWidth: 1,
    borderColor: '#E0B8CF',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  googleButtonText: {
    color: '#5B2A4F',
    fontSize: 15,
    fontWeight: '600',
  },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: '#ff0090ff',
  },
  orText: {
    marginHorizontal: 12,
    color: '#83627A',
    fontSize: 14,
  },
  footerLink: {
    color: '#D6336C',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '700',
  },
  secondaryLink: {
    marginTop: 16,
    alignItems: 'center',
  },
  secondaryLinkText: {
    color: '#9C1F54',
    fontSize: 15,
  },
  container: {
    flex: 1,
    backgroundColor: '#F8D7E7',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 16,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#F8D7E7',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  logoIcon: {
    fontSize: 56,
    marginTop: 24,
    marginBottom: 12,
  },
  logoImage: {
    width: 96,
    height: 96,
    resizeMode: 'contain',
    marginTop: 12,
    marginBottom: 6,
  },
  googleIcon: {
    width: 20,
    height: 20,
    marginRight: 12,
    resizeMode: 'contain',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 18,
    width: '100%',
    justifyContent: 'center',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E7BFD0',
    marginHorizontal: 8,
  },
  dividerLotus: {
    width: 28,
    height: 18,
    resizeMode: 'contain',
  },
});
