import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
    container: {
        flex: 1
    },
    content: {
        padding: 16,
        paddingBottom: 32,
    },
    screenTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#3E2245',
        marginBottom: 16,
        textAlign: 'center',
    },
    cardRow: {
        marginBottom: 24,
    },
    optionCard: {
        backgroundColor: '#FFFFFF',
        padding: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between'
    },
    optionCardActive: {
        borderWidth: 1,
        borderColor: COLORS.primary,
    },
    optionIcon: {
        width: 42,
        height: 42,
        borderRadius: 14,
        backgroundColor: '#FDE7F3',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
    },
    optionLabel: {
        flex: 1,
        fontSize: 16,
        fontWeight: '600',
        color: '#3E2245',
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 20,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 6,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#3E2245',
        marginBottom: 18,
    },
    input: {
        backgroundColor: '#F9F2F7',
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#3E2245',
        borderWidth: 1,
        borderColor: '#F0D8E5',
        marginBottom: 14,
    },
    saveButton: {
        backgroundColor: COLORS.primary,
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 8,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    notificationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 18,
    },
    notificationText: {
        flex: 1,
        marginRight: 12,
    },
    notificationTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#3E2245',
        marginBottom: 4,
    },
    notificationSubtitle: {
        color: '#7F5A77',
        fontSize: 14,
        lineHeight: 20,
    },
    card: {
        backgroundColor: '#FFFFFF',
        marginBottom: 20
    },
    
    description: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    optionText: {
        flex: 1,
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.gray,
    },
    sectionLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#aaa',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginLeft: 4,
  },

  containerPersonalData: { flex: 1, backgroundColor: '#f2f2f7' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#f2f2f7',
    borderBottomWidth: 0.5,
    borderBottomColor: '#ddd',
  },
  headerCancel: { fontSize: 16, color: COLORS.primary },
  headerTitle: { fontSize: 16, fontWeight: '600', color: '#000' },
  headerDone: { fontSize: 16, color: COLORS.primary, fontWeight: '600' },
  contentPersonalData: { padding: 20 },
  contentPasswordSecurity: { padding: 20 },
  avatarSection: { alignItems: 'center', marginBottom: 28 },
  avatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#fce4ec',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  avatarChange: { fontSize: 14, color: COLORS.primary },
  sectionLabelPersonalData: {
    fontSize: 11,
    fontWeight: '600',
    color: '#aaa',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginLeft: 4,
  },
  sectionLabelPasswordSecurity: {
    fontSize: 11,
    fontWeight: '600',
    color: '#aaa',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginLeft: 4,
    marginTop: 18,
  },
  group: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 24,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  fieldLabel: { width: 100, fontSize: 15, color: '#000' },
  fieldInput: { flex: 1, fontSize: 15, color: '#000', padding: 0 },
  separator: { height: 0.5, backgroundColor: '#e5e5e5', marginLeft: 16 },
});